### PR TITLE
Crowdin Guide Update June 2021

### PR DESCRIPTION
**Pull request by starktech23**
### Summary

Crowdin Guide Update June 2021

### CODE REVIEW

**Comment by SooluThomas** [comment]
Looks like you've deleted the guide?

**Comment by starktech23** [comment]
Oops let me check!

**Comment by starktech23** [comment]
It shows the updated guide on my fork, @SooluThomas am I missing something?

**Review by SooluThomas — APPROVED** [review]
No you're good! Thank you for updating the guide. This looks great! 🎉

**Comment by starktech23** [comment]
I think the binary in the "Files Changed" was not visible...? Not sure what happened :)

**Pull request merged**
