### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by MonitSharma**
### Summary

Related #4

### CODE REVIEW

**Comment by 0sophy1** [comment]
Hi @MonitSharma ! Thank you for your interest on joining Qiskit translation team. whenever you're ready, please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you!

**Comment by MonitSharma** [comment]
I have completed the task.

**Comment by starktech23** [comment]
Hi @MonitSharm, could you please re-submit your Crowdin request, this time with the link to this PR pasted in the Join prompt? See the steps mentioned above by @0sophy1 if you have questions about it. Please reply once you're done.

**Comment by MonitSharma** [comment]
I have done the step 4 and 5 as mentioned in the instructions , thank you

**Review by starktech23 — APPROVED** [review]
Added to Hindi Language.

**Pull request merged**
