### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by JulioLarrea**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by SooluThomas** [comment]
@JulioLarrea Please click on "CLA | not yet signed" and follow the instructions

**Comment by SooluThomas** [comment]
@JulioLarrea Thank you, now please click on https://crowdin.com/project/qiskit-docs/es-MX# and send a request to join the es_MX translations

**Comment by JulioLarrea** [comment]
> @JulioLarrea Thank you, now please click on https://crowdin.com/project/qiskit-docs/es-MX# and send a request to join the es_MX translations

Thank you.

**Review by SooluThomas — APPROVED** [review]
Joined Spanish, Mexico translations in Crowdin

**Pull request merged**
