### PR TITLE
Remove multiple staging workflows

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

This PR tries to fix the randomly failing gh-pages deploy build.

### CODE REVIEW

**Comment by SooluThomas** [comment]
Added `max-parallel=1`, this runs each job one after the other and so the `gh-pages` deployment worked. But this method is not ideal since the entire build took more than 11hrs to complete (1job=1hr). 

The best approach would be to get the commit message and parse the language mentioned in the commit message to run just that job.

**Comment by SooluThomas** [comment]
I think this is working well now!! 🎉

**Comment by SooluThomas** [comment]
So, I added `actions/upload-artifact@v2` and `actions/upload-artifact@v2`, so that the build files could be shared between jobs. But the upload artifact job turned out to run for all 13 languages (Total file count: 29505) which is unnecessary. The longest time taken for the build_docs job is **3h 52m 10s**. 😢 

I think that the upload-artifact step should be **run only once** and not more than that. The average time needed to upload 29505 files is approx 1hr, which makes the total build time more than 2 hrs 😭. 

Now, I'm waiting to see how long will it take to download artifacts and then push to gh-pages.

**Comment by SooluThomas** [comment]
Yay! Finally, the build is working correctly. The approximate build time is now **1hr 45mins**. Maybe I should consider adding a job for canceling previous workflows (maybe later). 🎉

**Comment by SooluThomas** [comment]
Another thing that I noticed is that the theme for some of the translations aren't showing up correctly like:
- https://qiskit-community.github.io/qiskit-translations/de_DE/
- https://qiskit-community.github.io/qiskit-translations/id_ID/
- https://qiskit-community.github.io/qiskit-translations/pt_PT/

And https://qiskit-community.github.io/qiskit-translations/bn_BN/ isn't working even though the files are in there.

**Review by mtreinish — APPROVED** [review]
This LGTM, the only complication I can see arising is because of L62 if any of the language builds fail it will block the deploy_docs job. But I don't think there is an alternative syntax for an ordering dependency without an implicit success condition on that.

**Pull request merged**
