### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by tsubasa-cc**
### Summary

Related #84

### CODE REVIEW

**Comment by SooluThomas** [comment]
@tsubasa-cc Please send joining request in [Crowdin](https://crowdin.com/project/qiskit-docs).

**Comment by tsubasa-cc** [comment]
Forgot to send join request in Crowdin. I sent it.

**Review by veenaiyuri — APPROVED** [review]
This user has made a join request in Crowdin successfully

**Comment by veenaiyuri** [comment]
skip ci

**Pull request merged**
