### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by acevik85**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @acevik85! Please go ahead and send join request to Qiskit-Docs project in Crowdin ([Step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#qiskit-documentation-localization-)).

**Comment by RajeshJeyapaul** [comment]
Willing to contribute to Tamil Language (India)

**Comment by SooluThomas** [comment]
Hi @RajeshJeyapaul, please open an issue as mentioned in the [instructions ](https://github.com/qiskit-community/qiskit-translations#how-to-add-a-new-language-to-translate) if there's no other issue opened for Tamil. Thank you for your interest to contribute!

**Comment by Pragadeeshwar** [comment]
#353

**Comment by SooluThomas** [comment]
@acevik85 I'm closing this PR due to inactivity. Feel free to reopen this and send a joining request to Turkish translations in Crowdin.

**Pull request closed without merging**
