### PR TITLE
add myself as a member Summary Related #10 & #196 https://crowdin.com/project/qiskit-docs/zh-tw#

### PR DESCRIPTION
**Pull request by Leon-Cha**
### Summary

Related #10 #196

### CODE REVIEW

**Comment by coruscating** [comment]
@Leon-Cha Please close your other pull requests if this is the correct one.

**Comment by coruscating** [comment]
@Leon-Cha Please write your name in English.

**Comment by Leon-Cha** [comment]
How to close pull requests?

**Comment by coruscating** [comment]
@Leon-Cha I've closed your other PRs for you. Can you write your name in English?

**Comment by SooluThomas** [comment]
@Leon-Cha To change your name to English, click on Files Changed (top right of the PR) -> Edit file -> type your name in English -> Commit changes.

**Review by SooluThomas — APPROVED** [review]
Joined Crowdin

**Pull request merged**
