### PR TITLE
Revalidation 2022 - Spanish (United)

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

Annual revalidation 2022 for Spanish (United)

### TODO

- [x] The members with NO ✅ will be removed from the list and crowdin after the TL(s) @clausia @roosado reviews this PR
- [x] Remove the users from list
- [x] remove ✅ to confirm the new list of contributors
- [x] remove the users from Crowdin

### CODE REVIEW

**Comment by clausia** [comment]
I confirm the list of members with a ✅.

Except for the member called _Pablo Vicente Greco_, who just joined on March 1st, I think he was not able to find out about the limit for revalidation, this member has been active in the project, and I have already confirmed with him that he wants to continue with the project.

**Comment by SooluThomas** [comment]
@clausia Thank you for the quick response. I have updated this in the commit https://github.com/qiskit-community/qiskit-translations/pull/861/commits/0d95075c39c69df6a2e6d010e013f743f8e39580.

**Comment by clausia** [comment]
> @clausia Thank you for the quick response. I have updated this in the commit [0d95075](https://github.com/qiskit-community/qiskit-translations/commit/0d95075c39c69df6a2e6d010e013f743f8e39580).

Thanks! @SooluThomas

**Comment by clausia** [comment]
@SooluThomas  Are the TLs responsible for removing Crowdin users?

**Comment by SooluThomas** [comment]
👍  Updated the list and removed users from Crowdin

**Review by veenaiyuri — APPROVED** [review]
Looks good to me.

**Pull request merged**
