### PR TITLE
Annual revalidation 2023 - French

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

Updated French LOCALIZATION CONTRIBUTORS file based on Revalidation 2023

### CODE REVIEW

**Comment by jmit34** [comment]
Thank you for organizing the 2023 review.
Agree.

**Comment by SooluThomas** [comment]
I have also received an email confirmation from @jmit34 to approve this PR. It probably must have been a mistake to close the PR. It was supposed to be an approval 😄

**Comment by jmit34** [comment]
Yes, correct. I would like to approve (not close)

**Review by 0sophy1 — APPROVED** [review]
Thank you so much @SooluThomas and @jmit34 updating list :)

**Pull request merged**
