### PR TITLE
Update LOCALIZATION_CONTRIBUTORS for Hindi Language

### PR DESCRIPTION
**Pull request by Hirmay**
I am familiar with Hindi and I wanna make sure that people who know Hindi but not English also have the opportunity to get familiarized with Qiskit

### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @Hirmay! Please go ahead and request to join Hindi translations in Crowdin. Please be sure to paste the link to this pull request in the comment box as mentioned in the [README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations).

**Comment by Hirmay** [comment]
Actually, I did that but there's some issue with pasting that link in Crowdin. Anupama Ray said she'll look into it, anyways thanks.

**Comment by SooluThomas** [comment]
@Hirmay Were you able to solve this issue?

**Comment by Hirmay** [comment]
I again reminded her on Crowdin, let's see what happens

**Comment by SooluThomas** [comment]
Yeah, feel free to reach out to me on [Qiskit Workspace on Slack](http://ibm.co/joinqiskitslack) -> @Soolu

**Comment by Hirmay** [comment]
I reached you out on slack but you seem busy when you're free can you please check it?
Thanks in advance

**Comment by SooluThomas** [comment]
Hi @Hirmay, I was off for a couple of weeks. I don't see any message on slack. Please let me know your name in slack so that I can ping you. Thanks.

**Review by SooluThomas — DISMISSED** [review]
Joined Hindi translations in Crowdin

**Review by SooluThomas — APPROVED** [review]

**Pull request merged**
