### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by LucasSousaReis**
Hello, my name is Lucas Sousa Reis I'm finishing my bachelor's degree in Computer Engineering. I have proficiency in English and have Portuguese as my mother language, I can contribute both as a translator or as a reviewer.

Related #6

### CODE REVIEW

**Comment by omarcostahamido** [comment]
Hi @LucasSousaReis, whenever you're ready, please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you

**Comment by LucasSousaReis** [comment]
@omarcostahamido  just completed steps 4 and 5.

**Review by omarcostahamido — APPROVED** [review]
Joined PT_UN translations in Crowdin

**Comment by omarcostahamido** [comment]
Thank you.

**Pull request merged**
