### PR TITLE
Adding myself to the PT-BR team

### PR DESCRIPTION
**Pull request by Alandroid**
### Summary

Related #6

### CODE REVIEW

**Comment by damn-glitch** [comment]
I am a new member.

**Comment by SooluThomas** [comment]
Hi @Alandroid, due to the recent changes in the languages, Portuguese, Brazilian and Portuguese have been unified to Portuguese (United). Please do [step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) again to join the translations in Crowdin. Thank you.

**Comment by Alandroid** [comment]
Hi @SooluThomas thanks for the notice! Job done :)

**Review by SooluThomas — APPROVED** [review]
Joined pt-un translations in Crowdin

**Pull request merged**
