### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by Binoy8080**
### Summary
I want to contribute to Begali language . I have bengali as a first language in my secondary school so I am well fluent in it. So I can translate into bengali effectively.   

Related #147

### CODE REVIEW

**Comment by ssangskriti** [comment]
@SooluThomas can you merge this pr please?

**Comment by Binoy8080** [comment]
> @SooluThomas can you merge this pr please?

Screenshot (32)
I am not very familiar in github and dont know how to merge,  but here it shows to me that  merging is blocked and it can be performed automatically with 1 approving review. see pic for reference

**Comment by Binoy8080** [comment]
or if this is wrong way please tell me hoe to merge the pr

**Review by starktech23 — APPROVED** [review]

**Comment by starktech23** [comment]
Added to Bengali Language.

**Pull request merged**
