### PR TITLE
Annual revalidation 2023 - Portuguese

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

Updated Portuguese LOCALIZATION CONTRIBUTORS file based on Revalidation 2023

### CODE REVIEW

**Comment by omarcostahamido** [comment]
LGTM

**Comment by SooluThomas** [comment]
waiting on response from @lgaleoti

**Comment by lgaleoti** [comment]
Hello Soolu and Omar! I really apologize for not having revalidated until now. I was unable to perform revalidation on Airtable. Apparently it's locked for editing. Help me with this? Tks!

**Review by clausia — APPROVED** [review]
LGTM

**Pull request merged**
