### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by 0sophy1**
Added "Soyoung Shin" to Korean contributor
(already join to crowdin)

### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by 0sophy1** [comment]
I signed CLA and already joined Crowdin Project. Thanks!

**Comment by SooluThomas** [comment]
Hi @0sophy1, I'm guessing that you've already signed the CLA by contributing to any of the repositories of Qiskit? Have you contributed to any Qiskit elements before?

**Comment by 0sophy1** [comment]
Hello!

 

I’m already doing translation in crowdin and I signed CLA with my first pull request. (maybe 2 weeks ago?)

 

Thanks!

**Comment by 0sophy1** [comment]
Thank you for your warm welcome!

**Pull request merged**
