### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by alex-cuenat**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by SooluThomas** [comment]
@alex-cuenat Please send a joining request in [Crowdin](https://crowdin.com/project/qiskit-docs)

**Comment by jmit34** [comment]
@SooluThomas I thinks Alex has already send a joinin request in Crowdin (which I wanted to review but accepted at the teime), does Alexandre need to make a new one ?

**Comment by SooluThomas** [comment]
@jmit34 Oh hmm.. This PR adds "Alexandre Cuenat". Am I missing something?

**Review by SooluThomas — APPROVED** [review]
Joined French translations in Crowdin

**Pull request merged**
