### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by smendoncabruna**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by omarcostahamido** [comment]
Hi Bruna, what is your crowdin username?

**Comment by smendoncabruna** [comment]
> 
> 
> Hi Bruna, what is your crowdin username?

Hi, it's smendoncabruna.

**Review by SooluThomas — APPROVED** [review]
Joined PT translations in Crowdin

**Comment by omarcostahamido** [comment]
Thank you.

**Pull request merged**
