### PR TITLE
Revalidation 2022 - Portuguese (United)

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

Annual revalidation 2022 for Portuguese (United)

### TODO

- [x] The members with NO ✅ will be removed from the list and crowdin after the TL(s) @lgaleoti reviews this PR
- [x] Remove the users from list
- [x] remove ✅ to confirm the new list of contributors
- [x] remove the users from Crowdin

### CODE REVIEW

**Comment by omarcostahamido** [comment]
At least Natália Capra Ferrazzo must have mistankenly forgotten to submit the form, because I remember reviewing a contribution of hers not that long ago! I'm messaging the members who didn't don't show a ✅ to double check if they don't want to revalidate.

**Comment by omarcostahamido** [comment]
messaged on crowdin and slack (those that I could find, not everyone on slack). tagging them here as a very last attempt to call for their attention and not have them being dropped: @Edmoita @gbamaral @apguilherme @vanildo @marcella-santana @caioafc @cassiopeabr @tiagofeits @LucasSousaReis @AndressaMerlo @nataliaferrazzo
Vocês contribuíram para o _Qiskit Localization Project_ nestes últimos 12 meses mas a equipa Qiskit não recebeu uma resposta positiva no formulário de revalidação anual. Por favor confirmem se realmente não pretendem mais fazer parte da equipa. Obrigado!

**Comment by SooluThomas** [comment]
@nataliaferrazzo I can add them manually. Thank you for confirming here.

**Comment by SooluThomas** [comment]
@omarcostahamido Does the list okay?

**Comment by omarcostahamido** [comment]
@SooluThomas as good as it can be right now.
Didn't get to hear from those 7 ppl still tagged [above](https://github.com/qiskit-community/qiskit-translations/pull/859#issuecomment-1105480101).
This was just to double check (even though it proved very much necessary in some cases). I had sent them all via slack and crowdin message the form when it was first shared, and Sam also sent it to everyone on crowdin message.
So, **LGTM**.

**Pull request merged**
