### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by wslu42**
add myself as a member
https://github.com/qiskit-community/qiskit-translations/pull/529

### Summary

Related #10 & #196

### CODE REVIEW

**Comment by starktech23** [comment]
Hi @wslu42! Please also add the link to this PR when you join both language teams on [Crowdin](https://crowdin.com/project/qiskit-docs).

**Comment by mingweii** [comment]
Add myself as a member

**Comment by wslu42** [comment]
@starktech23 hey sorry I am not sure what link should I add. I have joined the traditional Chinese team. Could you elaborate a little bit? Thanks!

WS

**Comment by starktech23** [comment]
Oh I see you've already joined Crowdin. I meant to ask if youcould add the URL to the PR (https://github.com/qiskit-community/qiskit-translations/pull/529) to the join prompt on Crowdin, but it's not an issue for now. Thanks!

**Comment by wslu42** [comment]
I see. Sorry that I wasn't familiar with pull request... Thanks!

**Review by coruscating — APPROVED** [review]

**Pull request merged**
