### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by VaniKH**
### Summary

Related #353

### CODE REVIEW

**Comment by VaniKH** [comment]
#353

**Comment by VaniKH** [comment]
#353

**Comment by VaniKH** [comment]
#353

**Comment by SooluThomas** [comment]
@VaniKH Please click on the "CLA | not yet signed"

**Comment by SooluThomas** [comment]
@VaniKH Please go ahead and send a joining request in [Crowdin](https://crowdin.com/project/qiskit-docs)

**Review by SooluThomas — APPROVED** [review]
joined Tamil translations in Crowdin

**Pull request merged**
