### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by mortezamudrick**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @mortezamudrick, whenever you're ready, please follow [steps 3 and below in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#qiskit-documentation-localization-) and request to join in Crowdin.

**Comment by mortezamudrick** [comment]
> Hi @mortezamudrick, whenever you're ready, please follow [steps 3 and below in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#qiskit-documentation-localization-) and request to join in Crowdin.

**Comment by mortezamudrick** [comment]
Hi @SooluThomas, thank you for your reminder. I've completed the step.

**Review by SooluThomas — APPROVED** [review]

**Comment by SooluThomas** [comment]
@mortezamudrick Please reach out to the translation lead and join the slack channel to learn and understand the team work flow before starting to translate. You can find your TL in [this link](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#translation-leads-as-of-oct-2022)

**Pull request merged**
