### PR TITLE
I want to contribute for PT-BR translation

### PR DESCRIPTION
**Pull request by nahumsa**
Add Nahum Rosa Cruz sá to PT-BR translation related to issue #6 – Translation leader Jose Gilberto Biondo Jr.

### Summary

Related #6

### CODE REVIEW

**Comment by SooluThomas** [comment]
No request was made in [Crowdin](https://crowdin.com/project/qiskit-docs) to join the PT-BR translations. I'm closing this PR for now.

@nahumsa Feel free to reopen this PR and request in Crowdin, if you are still interested in contributing.

**Comment by nahumsa** [comment]
Sorry, I thought that I made that request. 
But I am not able to reopen this PR.

**Comment by SooluThomas** [comment]
I just reopened the PR. Please send a joining request in Crowdin

**Review by SooluThomas — APPROVED** [review]
Joined Portuguese, Brazilian translations from Crowdin

**Pull request merged**
