### PR TITLE
Revalidation 2022 - Bengali

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

Annual revalidation 2022 for Bengali

### TODO

- [x] the members with **NO ✅** will be removed **from the list and crowdin** after Bengali TL @amitracal @ssangskriti reviews this PR
- [x] Remove the users from list
- [x] remove ✅ to confirm the new list of contributors
- [x] remove the users from Crowdin

### CODE REVIEW

**Comment by ssangskriti** [comment]
@SooluThomas I apologise for not filling up the revalidation form. I thought I did it. I am still willing  to contribute in this project. Kindly don't remove me if possible!

**Comment by amitracal** [comment]
At the last minute Debasmita Bhoumik, Souvik Ganguly and Gargi Roy has filled up the airtable, awaiting Jamiul Islam's response, with these included I approve

**Comment by amitracal** [comment]
Also please add Md. Sakibul Islam if possible

**Comment by SooluThomas** [comment]
> awaiting Jamiul Islam's response
as per the form filled out, Jamiul Islam has opted out from contributing

**Comment by SooluThomas** [comment]
Removed all deleted users from crowdin except. 

@amitracal Waiting on the status of Jamiul Islam. Once that's confirmed we should be good to go

**Comment by SooluThomas** [comment]
Confirmed with Abhijit offline to add Jamiul Islam 👍

**Pull request merged**
