### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by ftmzhrsckldr**
I would like to contribute Turkish translation.

### Summary

Related https://github.com/qiskit-community/qiskit-translations/issues/7

### CODE REVIEW

**Comment by SooluThomas** [comment]
@ftmzhrsckldr Please send a request to Crowdin as mentioned in the [steps 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations). Thank you!

**Comment by ftmzhrsckldr** [comment]
> @ftmzhrsckldr Please send a request to Crowdin as mentioned in the [steps 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations). Thank you!

Thank you, I have completed these steps.

**Comment by SooluThomas** [comment]
@ftmzhrsckldr Can you please let me know what your username in Crowdin is?

**Comment by ftmzhrsckldr** [comment]
> @ftmzhrsckldr Can you please let me know what your username in Crowdin is?

My Crowdin name is `Famara`.

**Pull request merged**
