### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by ageanwave**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by 0sophy1** [comment]
Hi @ageanwave , whenever you're ready, please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you!

**Comment by ageanwave** [comment]
> Hi @ageanwave , whenever you're ready, please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you!

All steps have been completed. Please approve the merge or let me know if there are any other steps left to be done. Thnak you.

**Comment by ageanwave** [comment]
> Hi @ageanwave , whenever you're ready, please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you!

Hi @0sophy1 , those are completed some time ago. Is there anything else left to do to get me added? Thank you!

**Review by ageanwave — COMMENTED** [review]
Stavros Lamprou added on the LOCALIZATION_CONTRIBUTORS file - Greek (GR)

**Review by 0sophy1 — APPROVED** [review]
Thank you @ageanwave ! I've confirmed you joined crowdin already. approve this PR

**Pull request merged**
