### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by amitracal**
### Summary

Related #147

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @amitracal, We need each member that you have added in the LOCALIZATION_CONTRIBUTORS list to open PRs of their own. This is a legal requirement that every contributor must sign the Contributors License Agreement (CLA). 

You can only add your name to the list. 

Thank you for your interest in contributing to this effort.

**Comment by amitracal** [comment]
I have notified others in the group and 2 of them have already made their
own pull requests

https://github.com/qiskit-community/qiskit-translations/pull/165

https://github.com/qiskit-community/qiskit-translations/pull/166

**Review by veenaiyuri — APPROVED** [review]
joined Bengali translations in Crowdin

**Comment by SooluThomas** [comment]
@amitracal I have removed the other names that you have added.
```
Amitava Chakraborty
Diptiman Dasgupta
Souvik Mazumder
Saswati Tripathy
```
Each individual has to create their own PR and sign the CLA. 
Thank you for your interest in contributing to this effort.

**Pull request merged**
