### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by rahulsust**
### Summary

Related <#147>

### CODE REVIEW

**Comment by rahulsust** [comment]
Hi @SooluThomas, I have requested to join as a translator in Crowdin Bengali. If you check if there is anything more to do, it will be appreciated. Thank you.

**Comment by SooluThomas** [comment]
@rahulsust I have notified the translation lead to check your joining request.

**Comment by amitracal** [comment]
@SooluThomas @rahulsust approved, sorry about the delay.

**Review by SooluThomas — APPROVED** [review]

**Comment by rahulsust** [comment]
> @rahulsust once you get the access please slack and I will get you connected with the team unless you are already connected.
@amitracal please give your slack handle.

**Comment by SooluThomas** [comment]
@rahulsust you can find the slack handles [here](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#translation-leads-as-of-oct-2022). Hope this helps

**Pull request merged**
