### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by bala-ceg**
### Summary

I have added my name to the LOCALIZATION_CONTRIBUTORS file under the language that I'd like to contribute.

Related #353

### CODE REVIEW

**Comment by SooluThomas** [comment]
@bala-ceg Please send joining request in [Crowdin](https://crowdin.com/project/qiskit-docs).

**Comment by SooluThomas** [comment]
Closing due to inactivity. Please reopen and reach-out out to the [Translation Lead](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#translation-leads-as-of-june-2021) if you're still interested. Thank you

**Comment by bala-ceg** [comment]
> @bala-ceg Please send joining request in [Crowdin](https://crowdin.com/project/qiskit-docs).

I requested in Crowdlin already

**Review by bala-ceg — COMMENTED** [review]
Reopening the PR

**Review by bala-ceg — COMMENTED** [review]
Reopening the PR

**Review by SooluThomas — APPROVED** [review]
Joined Tamil translations in Crowdin

**Pull request merged**
