### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by debasmita2102**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by ssangskriti** [comment]
Would you please add issue #147 to your commit and sign the CLA here please?

**Comment by debasmita2102** [comment]
Do  I need to do anything?


*Thanks and regards,*
*Yours sincerely,*

Debasmita Bhoumik
* Research Fellow*
*Advanced Computing & Microelectronics Unit*
*Indian Statistical Institute, Kolkata*

**Comment by ssangskriti** [comment]
you probably didn't sign Contributor License Agreement here yet 
image

**Comment by debasmita2102** [comment]
Now I have signed the Contributor License Agreement

**Review by SooluThomas — APPROVED** [review]
Joined Bengali translations in Crowdin

**Pull request merged**
