### PR TITLE
Update LOCALIZATION_CONTRIBUTORS in HINDI(HI)

### PR DESCRIPTION
**Pull request by ShivaniRajput11**
Signed-off-by: Shivani Rajput <shivanirajput1880@gmail.com>

### CODE REVIEW

**Comment by ShivaniRajput11** [comment]
@SooluThomas I have signed the Contribution License Agreement

**Comment by 0sophy1** [comment]
Hi @ShivaniRajput11 !  whenever you're ready, please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you

**Comment by ShivaniRajput11** [comment]
@0sophy1  done

**Review by SooluThomas — APPROVED** [review]
joined Hindi translations in Crowdin

**Pull request merged**
