### PR TITLE
Add Rathish Cholarajan

### PR DESCRIPTION
**Pull request by rathishcholarajan**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by rathishcholarajan** [comment]
@ManjulaGandhi could you please help merge this and add me to crowdin? I would like to update the current Tamil transliteration for Quantum Computing (குவாண்டம்) to the appropriate Tamil translation (குவையக் கணித்துவம்). What is your opinion on this? I think it's a widely accepted term.

**Comment by SooluThomas** [comment]
@rathishcholarajan Please do [step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you.

**Comment by rathishcholarajan** [comment]
@SooluThomas thanks! Done.

**Comment by ManjulaGandhi** [comment]
Thanks @SooluThomas  and Welcome @rathishcholarajan to Tamil translation team.

**Review by SooluThomas — APPROVED** [review]

**Pull request merged**
