### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by victor-von-pooh**
### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Review by kifumi — APPROVED** [review]

**Comment by SooluThomas** [comment]
@victor-von-pooh Whenever you're ready, please send a joining request to Crowdin ([instructions here](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations))

**Comment by SooluThomas** [comment]
On hold till @victor-von-pooh sends a joining request in Crowdin

**Comment by victor-von-pooh** [comment]
Sorry, I already did send joining request like 10 days ago

**Comment by SooluThomas** [comment]
@victor-von-pooh can you please resend it again or let me know your crowdin username

**Comment by victor-von-pooh** [comment]
> @victor-von-pooh can you please resend it again or let me know your crowdin username

@ hiroki_akita is mine.

**Comment by kifumi** [comment]
@SooluThomas I have just approved Hiroki at crowdin.  @victor-von-pooh Hiroki, sorry for my late response.

**Comment by victor-von-pooh** [comment]
@SooluThomas @kifumi Thank you so much!

**Pull request merged**
