### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by zgreco2000**
Add my name for Spanish

### Summary

Related #<replace_me_with_related_issue_number>

### CODE REVIEW

**Comment by clausia** [comment]
This user has already joined to crowdin 😃

**Review by clausia — DISMISSED** [review]

**Comment by clausia** [comment]
@zgreco2000 please sign the CLA license

**Review by clausia — COMMENTED** [review]
@zgreco2000 please sign the CLA license

**Comment by clausia** [comment]
Everything is ready with this PR, user has signed CLA license, and has been accepted in Crowdin platform.

**Review by SooluThomas — APPROVED** [review]

**Pull request merged**
