### PR TITLE
Related Issue# 286 for Urdu Language Addition

### PR DESCRIPTION
**Pull request by Haris-09**
I am adding myself as an Urdu proofreader and translator for the documentation.

### Summary

Related #<286>

### CODE REVIEW

**Review by veenaiyuri — COMMENTED** [review]
Need to resolve conflict.

**Comment by SooluThomas** [comment]
Hi @Haris-09! Thank you for your interest in contributing to Qiskit. Please follow step 4 and 5 in the [README.md](https://github.com/qiskit-community/qiskit-translations#to-sign-up-to-participate-in-translations)

>4. In the [Qiskit-Docs Crowdin project](https://crowdin.com/project/qiskit-docs), choose the language that you want to contribute to.<br/>
>5. Click the **Join** button and **paste the URL of your PR** in the dialog box where you are asked why you want to join the Crowdin project.

**Comment by SooluThomas** [comment]
@Haris-09 You can only add your name to this file.

**Comment by SooluThomas** [comment]
Updated this in commit https://github.com/qiskit-community/qiskit-translations/pull/291/commits/48c66f16987dfd0fb3f162b993b4ea6ca09e3fb7. 

Thank you for your interest in contributing to Qiskit. Please follow step 4 and 5 in the [README.md](https://github.com/qiskit-community/qiskit-translations#to-sign-up-to-participate-in-translations)

>4. In the [Qiskit-Docs Crowdin project](https://crowdin.com/project/qiskit-docs), choose the language that you want to contribute to.<br/>
>5. Click the **Join** button and **paste the URL of your PR** in the dialog box where you are asked why you want to join the Crowdin project.

**Comment by Haris-09** [comment]
Thanks, @SooluThomas for resolving the conflict. I have now completed step 4 and 5.

**Review by SooluThomas — APPROVED** [review]
Joined Urdu translations in Crowdin

**Pull request merged**
