### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by Rosy03**
- [x] I have added a related issue number.
- [x] I have read the CONTRIBUTING document on the Qiskit website. (Link - https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation)
- [x] I have added my name to the LOCALIZATION_CONTRIBUTORS file under the language that I'd like to contribute.

### Summary

Request for Bengali #147

### CODE REVIEW

**Review by amitracal — APPROVED** [review]
Reviewed and accepted

**Review by amitracal — DISMISSED** [review]

**Comment by amitracal** [comment]
This is reviewed and accepted by me.

**Review by veenaiyuri — APPROVED** [review]
Has joined Crowdin

**Review by veenaiyuri — APPROVED** [review]
Conflict has been resolved

**Pull request merged**
