### PR TITLE
Revalidation 2022 - Vietnamese

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

Annual revalidation 2022 for Vietnamese

### TODO

- [x] The members with NO ✅ will be removed from the list and crowdin after the TL(s) @RossyNguyen reviews this PR
- [x] Remove the users from list
- [x] remove ✅ to confirm the new list of contributors
- [x] remove the users from Crowdin

### CODE REVIEW

**Review by RossyNguyen — CHANGES_REQUESTED** [review]
Revalidation list for Vietnamese team with team member below are still active:
- Duy Lion Tran
- Valerie Nguyen
- To Duc Anh
- Bao Bach
- Hoang Van Do
- Phan Mai
- Duke Nguyen
(Sorry I don't know how to edit the file, so I added this request change with above active members)

**Comment by SooluThomas** [comment]
@RossyNguyen I don't see a `Phan Mai` in the file. Is that a typo. I have updated the list. Can you please check the list again and leave a comment? You don't have to edit the file. I can do it. 😄

**Comment by RossyNguyen** [comment]
Hi Soolu, 
Phan Mai is our newest member and she has been translating with us last time. Is it possible to add her to the list? Thanks

**Comment by SooluThomas** [comment]
@RossyNguyen what's her user name on Crowdin?

**Comment by SooluThomas** [comment]
Phan Mai will open a separate PR

**Pull request merged**
