### PR TITLE
Related #286 

### PR DESCRIPTION
**Pull request by javariya**
I am adding myself as an Urdu proofreader and translator for the documentation.

### Summary

Related #286

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @javariya! You should only add your name to the file

**Comment by SooluThomas** [comment]
Updated this in commit https://github.com/qiskit-community/qiskit-translations/pull/288/commits/bc3ed77e47314f9337aa17a4f3c84795d8dfdc20

Thank you for your interest in contributing to Qiskit. Please follow step 4 and 5 in the [README.md](https://github.com/qiskit-community/qiskit-translations#to-sign-up-to-participate-in-translations)

>4. In the [Qiskit-Docs Crowdin project](https://crowdin.com/project/qiskit-docs), choose the language that you want to contribute to.<br/>
>5. Click the **Join** button and **paste the URL of your PR** in the dialog box where you are asked why you want to join the Crowdin project.

**Comment by javariya** [comment]
Thank you @SooluThomas. I have completed steps 4 and 5.

**Review by SooluThomas — APPROVED** [review]
Joined Urdu translations in Crowdin

**Pull request merged**
